GET http://localhost:3000/subscribers?count=10&page=1&name=Mishu&subscribedToChannel=hello


###

GET http://localhost:3000/subscribers/6401d4e7f2d64ef5a59f3585

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Rafi Al Mahmud",
    "email":"r@gmail.com",
    "subscribedToChannel": "hello"
}

###

DELETE http://localhost:3000/subscribers/6401e450fb332db7f13f752d

###

PATCH http://localhost:3000/subscribers/6401e450fb332db7f13f752d
Content-Type: application/json

{
    "name": "John Doe Updated",
    "subscribedToChannel": "hello updated"
}