GET http://localhost:3000/user?count=10&page=1&sort_order=asc&sort_by=role


###

GET http://localhost:3000/user/640df1fd29136b68467a446a

###

POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"Mishu Baidya",
    "role":1,
    "phone":"01946918856"
}

###

DELETE http://localhost:3000/user/640858b9aafbe02576c1830a

###

PATCH http://localhost:3000/user/640df1fd29136b68467a446a
Content-Type: application/json

{
    "name": "Farhan"
}